#!/usr/bin/env ruby
ENV['RSPEC'] = 'true'     # allows autotest to discover rspec
ENV['AUTOTEST'] = 'true'  # allows autotest to run w/ color on linux
system((RUBY_PLATFORM.match?(/mswin|mingw/) ? 'autotest.bat' : 'autotest'), *ARGV) ||
  warn("Unable to find autotest.  Please install ZenTest or fix your PATH")
