#!/usr/bin/env ruby
begin
  load File.expand_path(File.dirname(__FILE__) + "/../vendor/plugins/cucumber/bin/cucumber")
rescue LoadError => e
  raise unless /cucumber/.match?(e.to_s)  

  require "rubygems"
  load File.join(Gem.bindir, "cucumber")
end